@url = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJGaWxtZXMgQVBJIiwic3ViIjoiYWRtaW4iLCJleHAiOjE3Nzc0Mzg5NDN9._Es92R-czpjThDWIo4cCFfaS1VlyS5UQbURW02P1RHE

POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idUsuario": 1,
    "descricao": "Salario",
    "tipo": "Entrada"
}

###
POST {{url}}/categorias
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idUsuario": 1,
    "descricao": "Mercado",
    "tipo": "Saída"
}

###
GET {{url}}/categorias
Authorization:  Bearer {{token}}

###
PUT {{url}}/categorias/1
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "idUsuario": 1,
    "descricao": "Décimo terceiro",
    "tipo": "Entrada"
}

###
GET {{url}}/categorias/1
Authorization:  Bearer {{token}}

###
DELETE {{url}}/categorias/1
Authorization:  Bearer {{token}}